import {displayName,hasJapaneseName,matchesName} from './names';
import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import type {OverlayStatus} from './vhp-overlay';

import {DEFAULT_FASCIA_OPACITY} from './fascia';
import {FasciaProvenance} from './fascia-provenance';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={vhpEnabled:false,vhpOpacity:.45,fasciaOpacity:DEFAULT_FASCIA_OPACITY,fascialSystemOpacity:DEFAULT_FASCIA_OPACITY,explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [vhpStatus,setVhpStatus]=useState<OverlayStatus>('idle');
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 // Base UI 1.7の内部閉じるボタンには翻訳用APIがないため、検索中だけ読み上げ名を補う。
 useEffect(()=>{if(panel!=='search')return;const translate=()=>document.querySelectorAll('[role="button"][aria-label="Dismiss"]').forEach(el=>el.setAttribute('aria-label','検索を閉じる'));const observer=new MutationObserver(translate);observer.observe(document.body,{childList:true,subtree:true});translate();return()=>observer.disconnect();},[panel]);

 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('解剖学データを読み込めませんでした。');return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError('解剖学データを読み込めませんでした。接続を確認して再読み込みしてください。');});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>matchesName(c.id,c.name,term)||((term==='fascial system'||term==='筋膜系')&&c.elements.some(id=>parts.get(id)?.system==='fascial-system'))).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query,parts]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const showFascialOnly=()=>{setChosen(null);setDetails(false);setPanel(null);setState(s=>({...s,vhpEnabled:false,visible:['fascial-system'],selected:[],isolate:false,rotate:false,reset:s.reset+1}));};
 const fascialControls=<div className="fascia-controls"><p className="coverage-note"><strong>筋膜：収録なし</strong><br/>現在使用しているBodyParts3Dデータでは、独立した名称付き筋膜モデルを確認できていません。</p><p className="coverage-note">表示可能な筋膜系は左右の腸脛靱帯と左右の手首屈筋支帯のみです。全身の筋膜を表すものではありません。</p>
 <Button className="fascia-only-button" onClick={showFascialOnly}>筋膜系だけ表示</Button>
 <details><summary>収録中の4構造を選ぶ</summary><p className="coverage-note">左右別の公式日本語名は未登録のため、英語名を保持しています。</p><div className="fascia-members">{atlas?.parts.filter(p=>p.system==='fascial-system').map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}>{displayName(p.conceptId,p.name)}<small>{p.id}</small></Button>)}</div></details>
 <details><summary>透明度・比較表示</summary><label className="fascia-opacity">筋膜系の透明度 <output>{Math.round(state.fascialSystemOpacity*100)}%</output><input type="range" aria-label="筋膜系の透明度" min="10" max="100" step="1" value={Math.round(state.fascialSystemOpacity*100)} onChange={e=>setState(s=>({...s,fascialSystemOpacity:Number(e.target.value)/100}))}/></label><p className="coverage-note">100%で不透明、10%で薄く表示します。初期値は65%です。</p><div className="fascia-presets"><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:['muscular','fascial-system'],selected:[],isolate:false}))}>筋肉＋筋膜系</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:['skeletal','muscular','fascial-system'],selected:[],isolate:false}))}>骨格＋筋肉＋筋膜系</Button></div></details></div>;

 return <main className="studio">
  {atlas&&<AnatomyScene onVhpStatus={setVhpStatus} atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> 人体3Dアトラス</div><h1>Human Atlas<Badge variant="outline" className="edition">筋膜研究版</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} 部位 <span>·</span> BodyParts3D</div></header>
  <div className="fascia-quick"><Button onClick={showFascialOnly}>筋膜系だけ表示</Button><span>収録4構造・全身の筋膜ではありません</span></div><nav className="top-actions" aria-label="探索メニュー"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="解剖学構造を検索"><Search size={18}/><span>構造を探す</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="このアトラスについて" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="解剖学レイヤー">
   <div className="panel-heading"><span>表示系統</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="系統を閉じる"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>すべて</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>骨格</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>臓器</Button></div>
   <div className="system-list"><section className="research-overlays" aria-label="研究用の追加レイヤー"><h3>研究用の追加レイヤー</h3><div className="research-toggle"><span>VHP Connective Tissue</span><Switch aria-label="VHP Connective Tissueを表示" checked={state.vhpEnabled??false} onCheckedChange={enabled=>setState(s=>({...s,vhpEnabled:enabled,explode:enabled?0:s.explode,isolate:false,selected:[]}))}/></div><p className="coverage-note">画像由来の結合組織の概観用試作。名称付き筋膜ではありません。別の献体を体表で粗く位置合わせしています。表面積は簡略化で約29%減少し、細い膜の形・連続性は確認できません。</p>{state.vhpEnabled&&<><p role="status">{vhpStatus==='loading'?'研究用モデルを読み込み中…':vhpStatus==='error'?'研究用モデルの読み込みに失敗しました。OFFにして再読み込みしてください。':vhpStatus==='ready'?'画像由来モデルを読み込みました。':'研究用モデルを準備中…'}</p><label className="fascia-opacity">研究用モデルの不透明度 <output>{Math.round((state.vhpOpacity??.45)*100)}%</output><input type="range" min="10" max="100" aria-label="研究用モデルの不透明度" value={Math.round((state.vhpOpacity??.45)*100)} onChange={e=>setState(s=>({...s,vhpOpacity:Number(e.target.value)/100}))}/></label><div className="fascia-presets"><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false,explode:0}))}>研究用モデルだけ表示</Button><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:['skeletal','muscular','fascial-system'],selected:[],isolate:false,explode:0}))}>骨格・筋肉と比較</Button></div>{(state.explode>.001||state.isolate)&&<p className="coverage-note">分解・個別表示中は、位置関係の誤解を避けるため研究用モデルを一時的に非表示にしています。</p>}</>}<details><summary>出典・処理・位置合わせの限界</summary><p>根拠：画像由来（Image-derived）<br/>VHP-Connective-Tissue-2025<br/>構造タイプ：connective-tissue-volume</p><p>1 mm画像から非ゼロ領域を抽出し、微小な孤立領域を除去して表面を簡略化しています。簡略化で表面積が28.7%減少し、連結成分は133,441個から4,101個に減っています。細い組織の形や連続性の確認には使えません。</p><p>体表サンプルの距離：平均24.6 mm、95%点71.4 mm。左右幅の差は約167 mm残ります。内部組織の正確な位置対応や診断・治療判断には使えません。</p><a href="https://doi.org/10.17632/zc53h3dcfg.1" target="_blank" rel="noreferrer">Stark・Sartori：男性VHPデータ（CC BY 4.0） ↗</a><a href="https://doi.org/10.1038/s41597-025-06134-x" target="_blank" rel="noreferrer">出典論文 ↗</a><a href="/models/fascia/vhp-atlas.json" target="_blank" rel="noreferrer">処理条件・変換行列・検証値 ↗</a></details></section>{[...SYSTEMS.filter(s=>s.id==='fascia'||s.id==='fascial-system'),...activeSystems.filter(s=>s.id!=='fascia'&&s.id!=='fascial-system')].map(s=><div key={s.id}><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" disabled={!counts[s.id]} title={`${s.name}だけ表示`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{s.id==='fascia'?'収録なし':counts[s.id]}</span></Button><Switch disabled={!counts[s.id]} checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`${s.name}を表示`} /></div>{s.id==='fascial-system'&&fascialControls}</div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} BP3D部位{state.vhpEnabled?' ＋ 研究モデル':''}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>すべて非表示</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="構造検索"><div className="panel-heading"><span>構造を探す</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="検索を閉じる"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>displayName(c.id,c.name)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="心臓、大腿骨、腸脛靱帯…" aria-label="日本語・英語・かなで構造を検索" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>一致する構造がありません。</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{displayName(c.id,c.name)}</span><span className="small-number">{c.elements.length} 部位</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'最大80件を表示します。詳しい名称で絞り込めます。':'日本語・英語・かな、またはAtlas IDで検索できます。'}</p></section>}
  <nav className="view-controls glass" aria-label="視点操作">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${['斜め','正面','側面','背面'][i]}から見る`} aria-label={`${['斜め','正面','側面','背面'][i]}から見る`}><span>{['斜','前','横','後'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'回転を停止':'人体を回転'} title="自動回転" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="視点とレイヤーをリセット" title="リセット" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?displayName(chosen.id,chosen.name):'選択した構造'):state.explode>.95?'構造を一覧表示':state.explode>.05?'構造を分解表示':state.vhpEnabled?(visibleCount===0?'VHP男性献体・概観用試作':'BodyParts3D ＋ VHP（粗い位置合わせ）'):'成人男性の参照モデル'}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="表示系統を開く"><Layers3 size={20}/><span>表示系統</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">構造を分解</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>組み立て</span><span>全パーツ分離</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="組み立ててリセット"><RotateCcw size={18}/><span>リセット</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?'ドラッグで移動':'ドラッグで回転'} <b>·</b> ピンチで拡大・縮小 <b>·</b> タップで詳細</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>出典・クレジット <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>人体モデルを準備中</strong><span>{progress}% · 読み込み中 {atlas?.parts.length.toLocaleString()??'2,234'} 部位</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>再読み込み</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?.name??'解剖学'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen&&displayName(chosen.id,chosen.name)}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system):''}</SheetDescription>{chosen&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">系統の概要・構造は原データに基づきます</span>}{chosen&&!hasJapaneseName(chosen.id)&&<p className="coverage-note">公式日本語名が未登録のため英語で表示しています。</p>}<div className="structure-meta"><span>Atlas ID<strong>{chosen?.id}</strong></span><span>選択中の部位数<strong>{state.selected.length.toLocaleString()}</strong></span></div><FasciaProvenance parts={selectedParts} conceptName={chosen?.name}/>{selectedParts.length>1&&<div className="member-list"><h3>含まれる構造</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{displayName(p.conceptId,p.name)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>ほか {selectedParts.length-50} 部位</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">解剖学データの出典を開く <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?'周囲の構造も表示':'この構造だけ表示'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>選択を解除</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">出典と収録範囲</div><SheetTitle className="structure-title">人体を立体的に理解する</SheetTitle><SheetDescription>BodyParts3Dの成人男性参照モデルを探索できます。</SheetDescription><div className="about-copy"><p><strong>成人男性 · BodyParts3D</strong><br/>成人男性の参照モデルに基づく2,234個のメッシュと3,432件の名称付き概念を収録しています。</p><p>すべての人体構造や個人差を収録しているわけではありません。1つの概念に複数の部位が含まれる場合があります。各メッシュは一度だけ描画します。</p><p>色と系統分類は探索のための表示です。形状はウェブ表示用に簡略化され、説明は一般的な学習用の内容です。診断・手術用のツールではありません。</p><h3>筋膜レイヤーの収録範囲</h3><p>現在の「筋膜系」は全身の筋膜を再現したものではありません。BodyParts3Dに独立した3Dメッシュとして存在し、出典を確認できた左右の腸脛靱帯と左右の手首屈筋支帯のみを表示しています。「筋膜」レイヤーには、独立した名称付き筋膜モデルは収録されていません。</p><p>「原データ由来」はBodyParts3Dが名称と形状を提供しているという意味で、献体画像からの直接抽出を意味しません。出典で確認できない分類は未確定としています。文献由来・画像由来・推定モデルは区別し、このレイヤーには含めていません。</p><h3>研究用の追加レイヤー</h3><p>VHP Connective Tissueを研究用に収録しています。Stark・Sartori（2025）の画像由来のコラーゲン含有結合組織で、名称付き筋膜ではありません。別の献体をBodyParts3Dの体表へ粗く位置合わせしています。体表サンプルの平均距離は約24.6 mm、95%点は約71.4 mmで、内部組織の精密な位置対応は未検証です。1 mmの画像から抽出・簡略化し、初めてONにした時だけ取得します。分解・個別表示中は一時的に非表示になります。</p><h3>教育・学習用</h3><p>教育、探索、解剖学の理解を目的としています。診断、手術計画、個別患者への医療判断、治療判断には使用しないでください。</p><h3>派生プロジェクト</h3><p>ashemagのHuman Atlasを基にした派生版です。原作者と解剖学データのクレジットを保持しています。</p><a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">原版Human Atlas ↗</a><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">クレジットと変更内容 ↗</a><h3>公式日本語名称</h3><p>BodyParts3D公式のIS-A・PARTOF名称表をFMA IDで照合しています。日本語名の未登録構造は英語を表示します。かなと英語でも検索できます。日本語名を独自に補ってはいません。</p><a href="https://dbarchive.biosciencedbc.jp/data/bodyparts3d/LATEST/isa_parts_list.txt" target="_blank" rel="noreferrer">公式日本語名称表 ↗</a><h3>出典</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">データのライセンス <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">原版の形状・名称データ <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">出典論文を読む <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
